# Generated by Django 5.0.7 on 2024-08-18 05:37

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GOCO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('shelf_life_value', models.FloatField()),
                ('shelf_life_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months')], max_length=10)),
                ('user_defined_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdpc_core_models.center')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=254, unique=True, verbose_name='username')),
                ('desired_salutation', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.')], default='Mr.', max_length=10)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can be blank or in international format.', regex='\\d{0,20}$')])),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('centre', models.ManyToManyField(blank=True, related_name='users', to='qdpc_core_models.center')),
                ('divisions', models.ManyToManyField(blank=True, related_name='users', to='qdpc_core_models.division')),
                ('usertype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qdpc_core_models.usertype')),
                ('role', models.ManyToManyField(help_text='Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='test_group', to='qdpc_core_models.role', verbose_name='Roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcceptanceTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('sampling_plan', models.FileField(upload_to='acceptance_test_results/')),
                ('reevaluation_frequency_value', models.PositiveIntegerField(default=12)),
                ('reevaluation_frequency_unit', models.CharField(choices=[('months', 'Months'), ('years', 'Years')], default='months', max_length=10)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='qdpc_core_models.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('procurement_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_size_value', models.FloatField()),
                ('packing_details', models.TextField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='qdpc_core_models.rawmaterial')),
                ('batch_size_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_sizes', to='qdpc_core_models.unit')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_no', models.CharField(max_length=255)),
                ('revision_no', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('approved_by', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='Rrawmaterial/Documents/')),
                ('validity', models.IntegerField(help_text='Validity in years')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdpc_core_models.documentcategory')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='qdpc_core_models.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_key', models.CharField(blank=True, max_length=50, null=True)),
                ('used_status', models.CharField(choices=[(0, 'UNUSED'), (1, 'USED')], default=0, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reset Password',
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='sources',
            field=models.ManyToManyField(related_name='raw_materials', to='qdpc_core_models.sources'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='suppliers',
            field=models.ManyToManyField(related_name='raw_materials', to='qdpc_core_models.suppliers'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file', models.FileField(upload_to='acceptance_test_results/')),
                ('test_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('acceptance_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='qdpc_core_models.acceptancetest')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptanceTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_value', models.FloatField()),
                ('test_date', models.DateField(default=django.utils.timezone.now)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('acceptance_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdpc_core_models.acceptancetest')),
                ('raw_material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='qdpc_core_models.rawmaterialbatch')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdpc_core_models.unit')),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdpc_core_models.usertype'),
        ),
    ]
