# Generated by Django 5.0.7 on 2024-08-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancetest',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
